//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphService.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GraphService.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tato hrana v grafu již existuje!.
        /// </summary>
        internal static string EdgeExists {
            get {
                return ResourceManager.GetString("EdgeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hrana nebyla v grafu nalezena!.
        /// </summary>
        internal static string EdgeNotFound {
            get {
                return ResourceManager.GetString("EdgeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oba vrcholy hrany jsou stejné! Nejsou povoleny smyčky!.
        /// </summary>
        internal static string EdgeWithSameVertices {
            get {
                return ResourceManager.GetString("EdgeWithSameVertices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nelze získat cestu, neboť graf není prozkoumán!.
        /// </summary>
        internal static string GraphNotExplored {
            get {
                return ResourceManager.GetString("GraphNotExplored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výpočty cest již nejsou platné a je potřeba provést přepočet!.
        /// </summary>
        internal static string InvalidCalculations {
            get {
                return ResourceManager.GetString("InvalidCalculations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data již nejsou platná a je potřeba je přegenerovat!.
        /// </summary>
        internal static string InvalidData {
            get {
                return ResourceManager.GetString("InvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadaný klíč v grafu již existuje!.
        /// </summary>
        internal static string KeyAlreadyExists {
            get {
                return ResourceManager.GetString("KeyAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null hodnota počátečního bodu!.
        /// </summary>
        internal static string StartKeyNull {
            get {
                return ResourceManager.GetString("StartKeyNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null hodnota cílového bodu!.
        /// </summary>
        internal static string TargetKeyNull {
            get {
                return ResourceManager.GetString("TargetKeyNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadaná položka v grafu již existuje!.
        /// </summary>
        internal static string ValueAlreadyExists {
            get {
                return ResourceManager.GetString("ValueAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadaná položka v grafu neexistuje!.
        /// </summary>
        internal static string ValueNotExists {
            get {
                return ResourceManager.GetString("ValueNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadaný vrchol v grafu neexistuje!.
        /// </summary>
        internal static string VertexNotExists {
            get {
                return ResourceManager.GetString("VertexNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrchol nebyl v grafu nalezen!.
        /// </summary>
        internal static string VertexNotFound {
            get {
                return ResourceManager.GetString("VertexNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zvolené vrcholy v grafu neexistují!.
        /// </summary>
        internal static string VerticesNotExist {
            get {
                return ResourceManager.GetString("VerticesNotExist", resourceCulture);
            }
        }
    }
}
