//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V programu již existuji data, chcete je přapsat?.
        /// </summary>
        internal static string DATA_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("DATA_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existující data.
        /// </summary>
        internal static string DATA_ALREADY_EXISTS_TITLE {
            get {
                return ResourceManager.GetString("DATA_ALREADY_EXISTS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba.
        /// </summary>
        internal static string ERROR_LABEL {
            get {
                return ResourceManager.GetString("ERROR_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V průběhu exportování se vyskytla chyba:
        ///
        ///.
        /// </summary>
        internal static string EXPORT_ERROR {
            get {
                return ResourceManager.GetString("EXPORT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba exportu.
        /// </summary>
        internal static string EXPORT_ERROR_TITLE {
            get {
                return ResourceManager.GetString("EXPORT_ERROR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V průběhu importování se vyskytla chyba:
        ///
        ///.
        /// </summary>
        internal static string IMPORT_ERROR {
            get {
                return ResourceManager.GetString("IMPORT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba importu.
        /// </summary>
        internal static string IMPORT_ERROR_TITLE {
            get {
                return ResourceManager.GetString("IMPORT_ERROR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap InfoPanel {
            get {
                object obj = ResourceManager.GetObject("InfoPanel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chcete otevřít soubor s uloženými daty?.
        /// </summary>
        internal static string OPEN_DATA_FILE {
            get {
                return ResourceManager.GetString("OPEN_DATA_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chcete otevřít soubor s uloženými daty?.
        /// </summary>
        internal static string OPEN_DATA_FILE_QUESTION {
            get {
                return ResourceManager.GetString("OPEN_DATA_FILE_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otevřít soubor.
        /// </summary>
        internal static string OPEN_FILE_TITILE {
            get {
                return ResourceManager.GetString("OPEN_FILE_TITILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otevřít soubor.
        /// </summary>
        internal static string OPEN_FILE_TITLE {
            get {
                return ResourceManager.GetString("OPEN_FILE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cesta vede do stejného vrcholu!.
        /// </summary>
        internal static string PATH_TO_SAME_VETEX {
            get {
                return ResourceManager.GetString("PATH_TO_SAME_VETEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zvolené vrcholy v grafu neexistují!.
        /// </summary>
        internal static string SELECTED_VERTEXES_NOT_EXITS {
            get {
                return ResourceManager.GetString("SELECTED_VERTEXES_NOT_EXITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neuložené změny.
        /// </summary>
        internal static string UNSAVED_CHANGES {
            get {
                return ResourceManager.GetString("UNSAVED_CHANGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máte neuložené změny grafu, chcete je uložit?.
        /// </summary>
        internal static string UNSAVED_CHANGES_ASK_TO_SAVE {
            get {
                return ResourceManager.GetString("UNSAVED_CHANGES_ASK_TO_SAVE", resourceCulture);
            }
        }
    }
}
