//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("700, 500")]
        public global::System.Drawing.Size MainformSize {
            get {
                return ((global::System.Drawing.Size)(this["MainformSize"]));
            }
            set {
                this["MainformSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400, 300")]
        public global::System.Drawing.Size MatrixformSize {
            get {
                return ((global::System.Drawing.Size)(this["MatrixformSize"]));
            }
            set {
                this["MatrixformSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1000, -1000")]
        public global::System.Drawing.Point MainformPosition {
            get {
                return ((global::System.Drawing.Point)(this["MainformPosition"]));
            }
            set {
                this["MainformPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1000, -1000")]
        public global::System.Drawing.Point DialogPosition {
            get {
                return ((global::System.Drawing.Point)(this["DialogPosition"]));
            }
            set {
                this["DialogPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1000, -1000")]
        public global::System.Drawing.Point MatrixformPosition {
            get {
                return ((global::System.Drawing.Point)(this["MatrixformPosition"]));
            }
            set {
                this["MatrixformPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1000, -1000")]
        public global::System.Drawing.Point HelpPosition {
            get {
                return ((global::System.Drawing.Point)(this["HelpPosition"]));
            }
            set {
                this["HelpPosition"] = value;
            }
        }
    }
}
